{{- $apiVersion := "batch/v1beta1" }}
{{- if .Values.cronjob.apiVersion -}}
{{- $apiVersion = .Values.cronjob.apiVersion -}}
{{- else if .Capabilities.APIVersions.Has "batch/v1" -}}
{{- $apiVersion = "batch/v1" }}
{{- end }}
apiVersion: {{ $apiVersion }}
kind: CronJob
metadata:
  name: {{ include "pantheon-backup.fullname" . }}
  labels:
    {{- include "pantheon-backup.labels" . | nindent 4 }}
spec:
  successfulJobsHistoryLimit: {{ .Values.cronjob.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.cronjob.failedJobsHistoryLimit }}
  concurrencyPolicy: {{ .Values.cronjob.concurrencyPolicy }}
  schedule: {{ .Values.cronjob.schedule | quote }}
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            {{- include "pantheon-backup.selectorLabels" . | nindent 12 }}
        spec:
        {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
        {{- end }}
          serviceAccountName: {{ include "pantheon-backup.serviceAccountName" . }}
          securityContext:
            {{- toYaml .Values.podSecurityContext | nindent 12 }}
          {{- if .Values.persistence.enabled }}
          initContainers:
            - name: fix-pvc-permissions
              image: alpine
              command:
                - "sh"
                - "-c"
                - "chown -R 1000:1000 /backups"
              volumeMounts:
                - name: cache
                  mountPath: /backups
          {{- end }}
          containers:
          - name: {{ .Chart.Name }}
            securityContext:
              {{- toYaml .Values.securityContext | nindent 14 }}
            image: "{{ include "pantheon-backup.image" . }}"
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            {{- with .Values.pantheon_backup.command }}
            command:
              {{- toYaml . | nindent 14 }}
            {{- end }}
            resources:
              {{- toYaml .Values.resources | nindent 14 }}
            volumeMounts:
              - name: config
                mountPath: /config/pantheon-backup
              {{- if .Values.persistence.enabled }}
              - name: cache
                mountPath: /backups
              {{- end }}
              {{- if .Values.extraVolumeMounts }}
              {{- toYaml .Values.extraVolumeMounts | nindent 14 }}
              {{- end }}
        {{- with .Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
        {{- end }}
        {{- with .Values.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
        {{- end }}
        {{- with .Values.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
        {{- end }}
          restartPolicy: {{ .Values.cronjob.restartPolicy }}
          volumes:
            - name: config
              configMap:
                name: {{ template "pantheon-backup.fullname" . }}-config
                defaultMode: 420
            {{- if .Values.persistence.enabled }}
            - name: cache
              persistentVolumeClaim:
                claimName: {{ template "pantheon-backup.fullname" . }}-cache
            {{- end }}
            {{- if .Values.extraVolumes }}
            {{- toYaml .Values.extraVolumes | nindent 12 }}
            {{- end }}
